redis:
  address: localhost:6379
  password:
  DB: 0

server:
  router:
    hostaddress: 192.168.0.153
    port: 5050
  maxuser: 1000

session:
  maxlifetime: 6000000000000

message:
  maxmessagesave: 5