redis:
  address: localhost:6379
  password:
  DB: 0

server:
  router:
    hostaddress: localhost #172.24.24.200
    port: 5050
  maxuser: 1000

session:
  maxlifetime: 600000000000

message:
  maxmessagesave: 5